reset;
option ampl_include 'C:\Users\Edielson\Documents\Researches\robust-network-optimization\ampl\reference';

model ReferenceBackupModel.mod;

data ReferenceBackupData.dat;

option log_file 'C:\Users\Edielson\Documents\Researches\robust-network-optimization\ampl\reference\BackupLog.log';

let K := (max{(s,d) in LINKS} capacity_P[s,d])+1;

option solver cplex;
option cplex_options 'mipgap=0.01 mipdisplay=3';


solve;
display CB;
#display B;

option log_file '';